DATABASE_PATH = "data/map_of_events.db"
DATA_DIR_PATH = "data/html_content"
INPUT_SITES_BASE_FILE_PATH = "resources/input_websites_base.json"
VISMO_RESEARCH_DATA_DIR_PATH = "data/tmp/vismo_research"
MUNICIPALITIES_OF_CR_FILE = "resources/municipalities_cr.csv"